<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>GymMateApi.CommentService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\Comments\" />
      <Folder Include="Core\" />
      <Folder Include="Infrastructure\" />
      <Folder Include="Persistance\" />
      <Folder Include="Presentation\" />
    </ItemGroup>

</Project>
